#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "afinn.net"
description: "Bending 0's and 1's to my will."
language: "en"

url: http://alan-finn.github.io
baseurl: ''

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 2
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: yourusername

enable-share: true
twitter: 
github: alan-finn
google: 

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/